inital_reset: true
enable_sync: true

# RGB
enable_color: true
rgb_camera.color_profile: 640x480x15
#rgb_camera.enable_auto_exposure: false

# Depth
enable_depth: true
depth_module.depth_profile: 640x480x15
align_depth.enable: true
clip_distance: 2.5

# IRs
enable_infra1: true
enable_infra2: true
depth_module.infra_profile: 640x480x15
depth_module.emitter_enabled: 0

# IMU
enable_gyro: true
enable_accel: true
gyro_fps: 200
accel_fps: 100
unite_imu_method: 2 # 0 -> none: no united imu topic
                    # 1 -> copy: gyro msg attached w/ LAST accel msg
                    # 2 -> linear_interpolation: interp accel to gyro t
hold_back_imu_for_frames: true